services:

  goservices.postgresdb:
    container_name: goservices.postgresdb
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@1798goServicesDb
      POSTGRES_DB: goServicesDb
    ports:
      - "5432:5432" # Map the container port to the host port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventorybackend

  goservices.productapi:
    container_name: goservices.productapi
    image: ${DOCKER_REGISTRY-}goservices.productapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000" # Map the container port to the host port
    environment:
      - ENVIRONMENT=production
      - DEFAULTPORT=3000
      - DB_USER=admin
      - DB_PASSWORD=admin@1798goServicesDb
      - DB_NAME=goServicesDb
      - DB_HOST=goservices.postgresdb
      - DB_PORT=5432
    networks:
      - inventorybackend
    depends_on:
      - goservices.postgresdb

networks:
  inventorybackend:
    name: inventorybackend
    driver: bridge

volumes:
  postgres_data:
